#server:
#  port: 8061

eureka:
  instance:
    hostname: https://discovery-service-ms.herokuapp.com/
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
       defaultZone: https://discovery-service-ms.herokuapp.com
       #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/