#server:
#  port: 80

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
---
spring:
  profiles: prod
eureka:
  instance:
    hostname: https://discovery-service-ms.herokuapp.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
       defaultZone: https://discovery-service-ms.herokuapp.com

    