# server:
#   port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: https://discovery-service-ms.herokuapp.com/eureka

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: country-service
        uri: lb://country-service
        predicates:
        - Path=/country/**
        filters:
        - RewritePath=/country/(?<path>.*), /$\{path}
      - id: city-service
        uri: lb://city-service
        predicates:
        - Path=/city/**
        filters:
        - RewritePath=/city/(?<path>.*), /$\{path}
#       - id: organization-service
#         uri: lb://organization-service
#         predicates:
#         - Path=/organization/**
#         filters:
#         - RewritePath=/organization/(?<path>.*), /$\{path}
