# server:
#   port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: https://discovery-service-ms.herokuapp.com/eureka

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
zuul:
  routes:
    department:
      path: /country/**
      serviceId: country-service
    employee:
      path: /city/**
      serviceId: city-service
#     organization:
#       path: /organization/**
#       serviceId: organization-service
